pos1  : [-0.23897,-0.49031,0.27365,-2.911,0.1928,2.436,1.6114]
pos2  : [0,0,0,0.0825,-0.0825,0, 0.088]
pos3  : [-0.04, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos4  : [-0.24136,-0.49052,0.27629,-2.9109,0.19466,2.4355,1.61]
pos5  : [-1.5708, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos6  : [-0.24644,-0.49107,0.2815,-2.9106,0.19874,2.4345,1.607]
pos7  : [-0.04, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos8  : [-0.25,-0.49153,0.2848,-2.9105,0.20172,2.4337,1.6049]
pos9  : [1.5708, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos10 : [-0.25172,-0.49177,0.28629,-2.9105,0.20322,2.4334,1.6038]
pos11 : [-0.04, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos12 : [-0.25606,-0.49245,0.28973,-2.9105,0.20717,2.4325,1.601]
pos13 : [-0.04, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos14 : [-0.25658,-0.49253,0.29011,-2.9106,0.20765,2.4324,1.6007]
pos15 : [-0.04, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos16 : [-0.26287,-0.49367,0.2942,-2.9108,0.21384,2.4311,1.5963]
pos17 : [-0.04, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos18 : [-0.26592,-0.4943,0.29581,-2.9111,0.21701,2.4304,1.594]
pos19 : [-0.04, -0.20, 0.20, -2.00, 0.018, 1.83, 1]
pos20 : [0,0,0,0.0825,-0.0825,0, 0.088]